// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1YR6DI3e4Ntde76ZU9hGvbdGXWhsdHm0',
    appId: '1:726889562486:web:cdcb44b9135a05d8d6fa57',
    messagingSenderId: '726889562486',
    projectId: 'socialnet-c2177',
    authDomain: 'socialnet-c2177.firebaseapp.com',
    storageBucket: 'socialnet-c2177.appspot.com',
    measurementId: 'G-6C1FS91PEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2kOhOP-gEGc5aqxxFNtJ-hJgbh-ngiw',
    appId: '1:726889562486:android:f92c8c271a6f1533d6fa57',
    messagingSenderId: '726889562486',
    projectId: 'socialnet-c2177',
    storageBucket: 'socialnet-c2177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mfShtSd2_ubwAmPn9emM_-9WhPTF5iU',
    appId: '1:726889562486:ios:63742b0e83b89dd5d6fa57',
    messagingSenderId: '726889562486',
    projectId: 'socialnet-c2177',
    storageBucket: 'socialnet-c2177.appspot.com',
    iosClientId: '726889562486-5np14oavb35595htm2a39u5vsh0qmudc.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5mfShtSd2_ubwAmPn9emM_-9WhPTF5iU',
    appId: '1:726889562486:ios:63742b0e83b89dd5d6fa57',
    messagingSenderId: '726889562486',
    projectId: 'socialnet-c2177',
    storageBucket: 'socialnet-c2177.appspot.com',
    iosClientId: '726889562486-5np14oavb35595htm2a39u5vsh0qmudc.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialnet',
  );
}
